### ISSUE TITLE
Moodle 4.4 Unknown format passed to format_text

### ISSUE THREAD

**Issue by teo-eskilled** [gbateson/moodle-qtype_essayautograde#85] opened 2024-10-29 05:18 UTC
Issue on marking page

$comment = $question->format_text($comment, $comment, $qa, $plugin, 'graderinfo', $question->id);

invalid second parameter on renderer.php function manual_comment(), should contain $question->graderinfoformat

![image](https://github.com/user-attachments/assets/527d5723-92f1-489e-8da6-a357f5206b31)

**Comment by mattgig** [comment] 2024-12-09 18:11
Please fix this issue, as it is causing problems in our installation (Moodle 4.5).

The fix suggested above solves the problem by changing line 372f.
```
  public function manual_comment(question_attempt $qa, question_display_options $options) {
        if ($options->manualcomment==question_display_options::EDITABLE) {
            $plugin = $this->plugin_name();
            $question = $qa->get_question();
            **$comment = $question->format_text($comment, $question->graderinfoformat, $qa, $plugin, 'graderinfo', $question->id);**
            $comment = $question->format_text($comment, $comment, $qa, $plugin, 'graderinfo', $question->id);
            $comment = html_writer::nonempty_tag('div', $comment, array('class' => 'graderinfo'));
        } else {
            $comment = ''; // comment is not currently editable
        }
        return $comment;
    }
```

**Comment by gbateson** [comment] 2024-12-12 02:56
Hi there Matthias and Teo-eskilled,
thanks for reporting this issue and supplying the fix.
I have modified the corresponding in the public release.
Please download from Github.com or Moodle.org at the next convenient opportunity.

Best regards,
Gordon

**Comment by gbateson** [comment] 2024-12-12 02:57
I think we can close this now, but if the issue is not fixed, please let me know. Gordon

**Closed by gbateson** 2024-12-12 02:57 UTC
