### ISSUE TITLE
if you have a table with text in it in the response template then it does not auto grade 

### ISSUE THREAD

**Issue by engrajabbar** [gbateson/moodle-qtype_essayautograde#39] opened 2020-08-26 03:05 UTC
if you have a response template defined, especially a table, then it does not auto-grade. The quiz can be submitted but in quiz review, it comes as not answered and no grade is assigned. 
 
![image](https://user-images.githubusercontent.com/70248820/91250577-86c00d80-e798-11ea-9783-e1a38ad0ed0a.png)

**Comment by gbateson** [comment] 2020-08-26 05:35
The issue is not as simple as "if you have a response template defined". Put more precisely, the issue is, "If you have a template that uses a lot of HTML code, ...".
This is a known issue, because the HTML code in the sample is treated as part of the "essay" text that the student submits. The plugin considers that the submitted response is too similar to the original sample, and as a result does not award a grade to the response.
One possible workaround is to use less HTML in your template.

**Comment by timaios2000** [comment] 2020-12-16 09:51
> The plugin considers that the submitted response is too similar to the original sample, and as a result does not award a grade to the response.

Is there workaround to disable this behavior? Could one just uncomment the code?

**Comment by timaios2000** [comment] 2020-12-16 13:12
I guess, I found the workaround. Setting thresholdpercent to zero turns off the similarity check. Maybe it's helpful to have this as an option in the activity preferences?

**Comment by gbateson** [comment] 2020-12-17 00:42
That's certainly one workaround. 
I will consider adding a switch to the settings. Thanks for that suggestion.
However, I think a more elegant solution would be to strip out HTML before comparing the similarity of the submission with the template or sample.

**Comment by gbateson** [comment] 2021-07-12 04:08
timaios2000, I have modified the code so that HTML tags are stripped before checking to see with the student response is similar to the response template. I believe this will fix the issue that you reported.

I will close this issue now, but please fee free to reopen it, if you feel the situation has not changed for you.

**Closed by gbateson** 2021-07-12 04:08 UTC
