### ISSUE TITLE
Terms in tables not evaluated

### ISSUE THREAD

**Issue by mattgig** [gbateson/moodle-qtype_essayautograde#36] opened 2020-07-28 18:24 UTC
When a student fills a table (given in the response template), the answers are not properly evaluated in Release 2020-07-15 (90). In the older relase this worked.

Example

Infinitive | Past simple | Present perfect
-- | -- | --
go | I went to town. | I have gone to the station.
can | I could ride a bicycle. | I have been able to drive a car.

When you define the keywords: went, gone, could, and been able to the are not recognized as correct when a students formulates a sentence with them or simply put the verb form into the table.

Even words before or after a table are not evaluated properly.

**Comment by gbateson** [comment] 2020-07-29 04:59
Hi Matt,
this is a very ingenious use of this question type. Thanks for sharing this technique.
I tried creating a question using your template and it seemed to behave as expected for me.
That is to say, the target words were recognized and the expected score was awarded.
So I'm a little puzzled when you say, "they are not recognized as correct" 🤔

Could you possible recreate your question on my development server, so that we can look at it together.
**URL:** [https://bateson.kochi-tech.ac.jp/37/](https://bateson.kochi-tech.ac.jp/37/)
**Course:** Course Fullname 101
**Username:** guestteacher
**Password:** taskchainv09

**Comment by mattgig** [comment] 2020-07-29 06:28
Hi Gordon,
thanks for your quick reply. I have just written a demo quiz on your server to demonstrate the problem. You find the explanation in the page underneath the quiz. It seems that the problem occurs either when there is more than one answer and the student's answer is partially wrong or when you include logical conjunctions like AND or OR with your keywords. As mentioned, this problem only occurs when there is a table in the response template.

**Comment by gbateson** [comment] 2020-07-29 07:20
Thanks for adding those questions for me to investigate. 
The problem is that the student response is substantially similar to the response template, so it is judged to be just a copy of the template.
I will change the code to ignore any HTML in the template and only compare the text content.
Please give me a few days to fix it.

**Comment by mattgig** [comment] 2020-07-29 11:19
Thanks again. Please, take your time.
At the moment, there is no hurry. We are still on summer holidays.

**Comment by gbateson** [comment] 2020-07-31 01:30
Hi Matt,
I think this issue is fixed now. There is sometimes an unexpected behavior of the response template contains quite a few words, and the student only supplies one or two new words. In this case, the student's response will be ignored, even if it contains some target phrases, because it will be judged to be too similar to the template to be considered for grading.

Please try out the latest version, 2020-07-30 (91), and let me know if it improves the performance of this question type when used with HTML TABLEs in the response template.

Best regards
Gordon

**Closed by gbateson** 2020-07-31 01:30 UTC

**Comment by mattgig** [comment] 2020-07-31 09:38
Hi Gordon

I just tested your new version, and it works now just as expected.
Thanks a lot for your great contributions to Moodle.

Just another thought: As I understand, the calculation of the grade is also based on the difference of the student's answer from what the teacher has provided in the response template. Would it be possible to make this comparison optional.

I'm asking because it would allow teachers tasks like the following:

Task 1:
The following sentences contains a mistake. Correct it:
She have three brothers.
For this to work with several sentences the keyword should be defined as something as "She has three".

At the moment this works when the response template is empty and the student either copies the text into the answer field or types it by hand.

Of course a task like this can be achieved with other tools, but it would become very simple for teachers to write any type of questions where student have to make small changes.

Warmest regards
Matthias
