### ISSUE TITLE
Error message and wrong submission

### ISSUE THREAD

**Issue by timaios2000** [gbateson/moodle-qtype_essayautograde#26] opened 2019-05-31 00:35 UTC
Hi Gordon, we face the very same issue that Ritchie Langley has described in a comment in the Plugin area on moodle.org

If a user takes more than x mins to type their answer. They get an error saying "You have entered data outside the normal sequence." The user hasn't clicked back or forward, just submit. Then, what is submitted and graded is not what the user has typed.

Would be great if you can check what's going wrong.

Roland

**Comment by gbateson** [comment] 2019-05-31 05:23
I see. Thanks for reporting this.

The time limit comes from the quiz, right? Not from the question.
I wonder what other question type do about this. For example, what happens if you take too long on an normal essay question? Could you try that and let me know?

Thanks,
Gordon

**Comment by timaios2000** [comment] 2019-05-31 13:25
Hello Gordon,

Thanks for your reply. The issue has nothing to do with the time limit option, which not activated.

I did some research on the error message and found this discussion on moodle.org

https://moodle.org/mod/forum/discuss.php?d=344367

Obviously, it’s not an issue of your very useful question type.

Thanks, Roland

**Comment by gbateson** [comment] 2020-01-06 00:15
Thanks Roland, for finding the cause of the problem.
I'm pleased to hear that it has been fixed in Moodle 3.6 and 3.7.
I'll close this issue now.
Best regards, Gordon

**Closed by gbateson** 2020-01-06 00:15 UTC
